AllCops:
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false
