twitter: &twitter
  twitter_api_key: <%= ENV['TWITTER_API_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_SECRET_KEY'] %>

# development:
#   secret_key_base: <hogehoge>
#   <<: *twitter
#
# test:
#   secret_key_base: <fugafuga>
#   <<: *twitter
#
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#   <<: *twitter
